#!/usr/bin/env node
// Builds ./ds-bundle (tokens + fonts + CSS recipes + foundation cards) from the Compose theme.
// Haunt's components are Compose, which can't ship as a React bundle, so this replaces the
// design-sync converter. Run from the repo root: node .design-sync/build.mjs
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const THEME = 'shared/ui/src/commonMain/kotlin/io/github/crockalet/haunt/ui/theme';
const FONTS = 'shared/ui/src/commonMain/composeResources/font';
const DS = '.design-sync';
const OUT = 'ds-bundle';

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const hex2 = (n) => n.toString(16).padStart(2, '0');

// Compose Color(0xAARRGGBB) or Color(r, g, b, (a * 255).toInt()) -> CSS.
function cssColor(expr) {
  let m = expr.match(/^Color\(0x([0-9A-Fa-f]{8})\)$/);
  if (m) {
    const [a, r, g, b] = m[1].match(/../g).map((h) => parseInt(h, 16));
    return a === 255 ? `#${hex2(r)}${hex2(g)}${hex2(b)}`.toUpperCase() : `rgb(${r} ${g} ${b} / ${+(a / 255).toFixed(3)})`;
  }
  m = expr.match(/^Color\((\d+),\s*(\d+),\s*(\d+),\s*\(([\d.]+)f\s*\*\s*255\)\.toInt\(\)\)$/);
  if (m) return `rgb(${m[1]} ${m[2]} ${m[3]} / ${+m[4]})`;
  throw new Error(`unparsed colour: ${expr}`);
}

function palette(src, name) {
  const body = src.match(new RegExp(`val ${name} = HauntColors\\(([\\s\\S]*?)\\n\\)`))[1];
  const out = {};
  for (const m of body.matchAll(/^\s*(\w+) = (Color\(.*\)),$/gm)) out[m[1]] = cssColor(m[2]);
  return out;
}

const colorsKt = readFileSync(join(THEME, 'HauntColors.kt'), 'utf8');
const light = palette(colorsKt, 'LightHauntColors');
const dark = palette(colorsKt, 'DarkHauntColors');
const danger = cssColor(colorsKt.match(/val danger: Color = (Color\(0x\w+\))/)[1]);
light.danger = dark.danger = danger;
const folders = {};
for (const m of colorsKt.matchAll(/val (Blue|Green|Orange) = (Color\(0x\w+\))/g)) folders[m[1]] = cssColor(m[2]);

const typeKt = readFileSync(join(THEME, 'HauntTypography.kt'), 'utf8');
const WEIGHTS = { Normal: 400, Medium: 500, SemiBold: 600, Bold: 700 };
const typeScale = [];
for (const m of typeKt.matchAll(/val (\w+) = ([sm])\(([\d.]+)f, FontWeight\.(\w+)(?:, (-?[\d.]+)f)?(?:, (?:lineHeight = )?([\d.]+)f)?\)/g)) {
  typeScale.push({ name: m[1], mono: m[2] === 'm', size: +m[3], weight: WEIGHTS[m[4]], spacing: m[5] ? +m[5] : 0, lineHeight: m[6] ? +m[6] : null });
}

const themeKt = readFileSync(join(THEME, 'HauntTheme.kt'), 'utf8');
const radii = {};
for (const m of themeKt.matchAll(/val (\w+) = RoundedCornerShape\((?:percent = )?(\d+)(\.dp)?\)/g)) radii[m[1]] = m[3] ? `${m[2]}px` : '999px';

// Springs (mass 1, from 0 to 1) sampled into CSS linear() easings.
const motionKt = readFileSync(join(THEME, 'HauntMotion.kt'), 'utf8');
function spring(zeta, k) {
  const w = Math.sqrt(k);
  const x = (t) => zeta < 1
    ? 1 - Math.exp(-zeta * w * t) * (Math.cos(w * Math.sqrt(1 - zeta ** 2) * t) + (zeta / Math.sqrt(1 - zeta ** 2)) * Math.sin(w * Math.sqrt(1 - zeta ** 2) * t))
    : 1 - Math.exp(-w * t) * (1 + w * t);
  let T = 0.01;
  for (let t = 0.01; t < 3; t += 0.001) if (Math.abs(1 - x(t)) > 0.001) T = t;
  const n = 32;
  const pts = Array.from({ length: n + 1 }, (_, i) => +x((T * i) / n).toFixed(4));
  pts[n] = 1;
  return { duration: Math.round(T * 1000), easing: `linear(${pts.join(', ')})` };
}
const springs = {};
for (const m of motionKt.matchAll(/fun <T> (\w+)\(\)[^=]*= spring\(dampingRatio = ([\d.]+)f, stiffness = ([\d.]+)f\)/g)) springs[m[1]] = spring(+m[2], +m[3]);

rmSync(OUT, { recursive: true, force: true });
for (const d of ['fonts', 'tokens', 'guidelines/screens']) mkdirSync(join(OUT, d), { recursive: true });

// Fonts.
const fontFaces = [];
for (const f of readdirSync(FONTS).filter((f) => f.endsWith('.ttf')).sort()) {
  copyFileSync(join(FONTS, f), join(OUT, 'fonts', f));
  const family = f.startsWith('jetbrains') ? 'JetBrains Mono' : 'Plus Jakarta Sans';
  const weight = WEIGHTS[{ regular: 'Normal', medium: 'Medium', semibold: 'SemiBold', bold: 'Bold' }[f.replace(/.*_(\w+)\.ttf$/, '$1')]];
  fontFaces.push(`@font-face{font-family:"${family}";src:url("${f}") format("truetype");font-weight:${weight};font-style:normal;font-display:swap}`);
}
writeFileSync(join(OUT, 'fonts/fonts.css'), fontFaces.join('\n') + '\n');

const vars = (p) => Object.entries(p).map(([k, v]) => `  --hn-${kebab(k)}: ${v};`).join('\n');
const HEAD = '/* Generated by .design-sync/build.mjs from shared/ui/.../theme. Do not edit. */\n';
writeFileSync(join(OUT, 'tokens/colors.css'), `${HEAD}
:root {
  color-scheme: light;
${vars(light)}
${Object.entries(folders).map(([k, v]) => `  --hn-folder-${k.toLowerCase()}: ${v};`).join('\n')}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${vars(dark).replace(/^/gm, '  ')}
  }
}
:root[data-theme="dark"], [data-theme="dark"] {
  color-scheme: dark;
${vars(dark)}
}
[data-theme="light"] {
  color-scheme: light;
${vars(light)}
}
`);

writeFileSync(join(OUT, 'tokens/typography.css'), `${HEAD}
:root {
  --hn-font-sans: "Plus Jakarta Sans", system-ui, sans-serif;
  --hn-font-mono: "JetBrains Mono", ui-monospace, monospace;
}
${typeScale.map((t) => `.hn-${kebab(t.name)}{font-family:var(--hn-font-${t.mono ? 'mono' : 'sans'});font-size:${t.size}px;font-weight:${t.weight};letter-spacing:${t.spacing}px;line-height:${t.lineHeight ?? 'normal'}}`).join('\n')}
`);

writeFileSync(join(OUT, 'tokens/shape.css'), `${HEAD}
:root {
${Object.entries(radii).map(([k, v]) => `  --hn-radius-${kebab(k)}: ${v};`).join('\n')}
}
`);

writeFileSync(join(OUT, 'tokens/motion.css'), `${HEAD}
:root {
${Object.entries(springs).map(([k, s]) => `  --hn-spring-${k}: ${s.easing};\n  --hn-spring-${k}-duration: ${s.duration}ms;`).join('\n')}
}
`);

copyFileSync(join(DS, 'recipes.css'), join(OUT, 'tokens/recipes.css'));
writeFileSync(join(OUT, 'styles.css'), `/* Haunt Glass design tokens and recipes. */
@import url("fonts/fonts.css");
@import url("tokens/colors.css");
@import url("tokens/typography.css");
@import url("tokens/shape.css");
@import url("tokens/motion.css");
@import url("tokens/recipes.css");
`);

// Foundation cards: hand-authored in .design-sync/cards/<Name>.html.
for (const f of readdirSync(join(DS, 'cards')).filter((f) => f.endsWith('.html'))) {
  const name = f.replace(/\.html$/, '');
  mkdirSync(join(OUT, 'components/foundations', name), { recursive: true });
  copyFileSync(join(DS, 'cards', f), join(OUT, 'components/foundations', name, f));
}

copyFileSync(join(DS, 'guidelines.md'), join(OUT, 'guidelines/glass.md'));
for (const f of readdirSync('docs/screenshots').filter((f) => f.endsWith('.png'))) copyFileSync(join('docs/screenshots', f), join(OUT, 'guidelines/screens', f));

const conventions = readFileSync(join(DS, 'conventions.md'), 'utf8');
writeFileSync(join(OUT, 'README.md'), `${conventions.trim()}

## Token reference

### Colours (light / dark)
${Object.keys(light).map((k) => `- \`--hn-${kebab(k)}\`: ${light[k]} / ${dark[k]}`).join('\n')}
${Object.entries(folders).map(([k, v]) => `- \`--hn-folder-${k.toLowerCase()}\`: ${v}`).join('\n')}

### Type classes
${typeScale.map((t) => `- \`.hn-${kebab(t.name)}\`: ${t.mono ? 'mono' : 'sans'} ${t.size}px / ${t.weight}${t.spacing ? `, ${t.spacing}px tracking` : ''}`).join('\n')}

### Radii
${Object.entries(radii).map(([k, v]) => `- \`--hn-radius-${kebab(k)}\`: ${v}`).join('\n')}

### Springs
${Object.entries(springs).map(([k, s]) => `- \`--hn-spring-${k}\` with \`--hn-spring-${k}-duration\` (${s.duration}ms)`).join('\n')}
`);

writeFileSync(join(OUT, '_ds_needs_recompile'), JSON.stringify({ by: 'design-sync-cli' }));
console.log(`colours ${Object.keys(light).length}, type ${typeScale.length}, radii ${Object.keys(radii).length}, springs ${Object.keys(springs).length}, fonts ${fontFaces.length}`);
